YOURLANG_DICT = {
                   'a':'', 
                   'an':'', 
                   'the':'', 

                   'although':'', 
                   'and':'', 
                   'as':'', 
                   'because':'', 
                   'but':'', 
                   'for':'', 
                   'if':'', 
                   'nor':'', 
                   'or':'', 
                   'so':'', 
                   'than':'', 

                   'after':'', 
                   'before':'', 
                   'how':'', 
                   'later':'', 
                   'now':'', 
                   'since':'', 
                   'soon':'', 
                   'then':'', 
                   'until':'', 
                   'whereas':'', 
                   'whether':'', 
                   'while':'', 
                   'why':'', 
                   'yet':'', 

                   'he':'',            'him':'',          'his':'', 
                   'I':'',             'me':'',           'mine':'',         'my':'', 
                   'it':'',            'that':'',         'these':'',        'this':'',            'those':'', 
                   'she':'',           'her':'',          'hers':'', 
                   'they':'',          'them':'', 
                   'we':'',            'us':'',           'our':'',          'ours':'', 
                   'you':'',           'you all':'',      'your':'',         'yours':'', 

                   'self':'',          'himself':'',      'herself':'',      'itself':'',          'myself':'',     'yourself':'', 
                   'selves':'',        'themselves':'',   'ourselves':'',    'yourselves':'', 

                   'what':'',          'whatever':'', 
                   'when':'',          'whenever':'', 
                   'where':'',         'wherever':'', 
                   'which':'',         'whichever':'', 
                   'who':'',           'whoever':'', 
                   'whom':'',          'whomever':'', 
                   'whose':'', 

                   'am':'', 
                   'are':'', 
                   'be':'', 
                   'being':'', 
                   'did':'', 
                   'do':'', 
                   'does':'', 
                   'done':'', 
                   'had':'', 
                   'has':'', 
                   'have':'', 
                   'is':'', 
                   'was':'', 
                   'were':'', 

                   'all':'', 
                   'another':'', 
                   'any':'', 
                   'anybody':'', 
                   'anyone':'', 
                   'anything':'', 
                   'both':'', 
                   'each':'', 
                   'either':'', 
                   'everybody':'', 
                   'everyone':'', 
                   'everything':'', 
                   'few':'', 
                   'many':'', 
                   'most':'', 
                   'neither':'', 
                   'nobody':'', 
                   'none':'', 
                   'no one':'', 
                   'nothing':'', 
                   'one':'', 
                   'only':'', 
                   'other':'', 
                   'others':'', 
                   'several':'', 
                   'some':'', 
                   'somebody':'', 
                   'someone':'', 
                   'something':'', 
                   'such':'', 

                   'can':'', 
                   'could':'', 
                   'may':'', 
                   'might':'', 
                   'must':'', 
                   'shall':'', 
                   'will':'', 
                   'would':'', 

                   'that':'', 
                   'these':'', 
                   'this':'', 
                   'those':'', 
                   'those':'', 

                   'has':'',           'have':'', 

                   'aboard':'', 
                   'about':'', 
                   'above':'', 
                   'across':'', 
                   'against':'', 
                   'along':'', 
                   'amid':'', 
                   'among':'', 
                   'around':'', 
                   'as':'', 
                   'at':'', 
                   'before':'', 
                   'behind':'', 
                   'beneath':'', 
                   'beside':'', 
                   'between':'', 
                   'beyond':'', 
                   'but':'', 
                   'by':'', 
                   'concerning':'', 
                   'considering':'', 
                   'despite':'', 
                   'down':'', 
                   'during':'', 
                   'except':'', 
                   'following':'', 
                   'for':'', 
                   'from':'', 
                   'in':'', 
                   'inside':'', 
                   'into':'', 
                   'like':'', 
                   'minus':'', 
                   'near':'', 
                   'next':'', 
                   'of':'', 
                   'off':'', 
                   'on':'', 
                   'onto':'', 
                   'opposite':'', 
                   'out':'', 
                   'outside':'', 
                   'over':'', 
                   'past':'', 
                   'per':'', 
                   'plus':'', 
                   'regarding':'', 
                   'round':'', 
                   'save':'', 
                   'since':'', 
                   'than':'', 
                   'through':'', 
                   'till':'', 
                   'to':'', 
                   'toward':'', 
                   'under':'', 
                   'underneath':'', 
                   'unlike':'', 
                   'until':'', 
                   'upon':'', 
                   'versus':'', 
                   'via':'', 
                   'with':'', 
                   'within':'', 
                   'without':'',

                   'thing':'', 

                   'maybe':'', 
                   'no':'', 
                   'yes':'', 

                   'mean':'', 
                   'meant':'', 
                   'say':'', 

                   'down':'', 
                   'backward':'', 
                   'backwards':'', 
                   'far':'', 
                   'farther':'', 
                   'further':'', 
                   'foward':'', 
                   'left':'', 
                   'near':'', 
                   'return':'', 
                   'right':'', 
                   'toward':'', 
                   'towards':'', 
                   'up':'', 

                   'east':'', 
                   'north':'',         'northeast':'', 'northwest':'', 
                   'south':'',         'southeast':'', 'southwest':'', 
                   'west':'', 

                   'black':'', 
                   'blue':'', 
                   'brown':'', 
                   'green':'', 
                   'gray':'', 
                   'grey':'', 
                   'pink':'', 
                   'purple':'', 
                   'red':'', 
                   'white':'', 
                   'yellow':'', 

                   'do that':'', 
                   'what':'', 

                   'had':'',                'had to':'', 
                   'has':'',                'has to':'', 
                   'have':'',               'have to':'', 

                   'of me':'',              'of mine':'', 
                   'of us':'',              'of ours':'', 
                   'of you':'',             'of yours':'', 

                   'he can':'',             'can he':'', 
                   'he could':'',           'could he':'', 
                   'he did':'',             'did he':'', 
                   'he does':'',            'does he':'', 
                   'he is':'',              'is he':'', 
                   'he may':'',             'may he':'', 
                   'he might':'',           'might he':'', 
                   'he must':'',            'must he':'',         
                   'he shall':'',           'shall he':'', 
                   'he should':'',          'should he':'', 
                   'he was':'',             'was he':'', 
                   'he will':'',            'will he':'', 
                   'he would':'',           'would he':'', 

                   'she can':'',            'can she':'', 
                   'she could':'',          'could she':'', 
                   'she did':'',            'did she':'',  
                   'she does':'',           'does she':'', 
                   'she is':'',             'is she':'', 
                   'she may':'',            'may she':'', 
                   'she might':'',          'might she':'', 
                   'she must':'',           'must she':'', 
                   'she shall':'',          'shall she':'', 
                   'she should':'',         'should she':'', 
                   'she was':'',            'was she':'', 
                   'she will':'',           'will she':'', 
                   'she would':'',          'would she':'', 

                   'i am':'',               'am i':'', 
                   'i can':'',              'can i':'', 
                   'i could':'',            'could i':'', 
                   'i did':'',              'did i':'', 
                   'i do':'',               'do i':'', 
                   'i may':'',              'may i':'', 
                   'i might':'',            'might i':'', 
                   'i must':'yos',          'must i':'', 
                   'i shall':'',            'shall i':'', 
                   'i should':'',           'should i':'', 
                   'i was':'',              'was i':'', 
                   'i will':'yol',          'will i':'', 
                   'i would':'',            'would i':'', 

                   'it can':'',             'can it':'', 
                   'it could':'',           'could it':'', 
                   'it did':'',             'did it':'', 
                   'it does':'',            'does it':'', 
                   'it is':'',              'is it':'', 
                   'it may':'',             'may it':'', 
                   'it must':'',            'must it':'', 
                   'it might':'',           'might it':'', 
                   'it shall':'',           'shall it':'', 
                   'it should':'',          'should it':'', 
                   'it was':'',             'was it':'', 
                   'it will':'',            'will it':'', 
                   'it would':'',           'would it':'', 

                   'that can':'',           'can that':'', 
                   'that could':'',         'could that':'', 
                   'that did':'',           'did that':'', 
                   'that does':'',          'does that':'', 
                   'that is':'',            'is that':'', 
                   'that may':'',           'may that':'', 
                   'that might':'',         'might that':'', 
                   'that shall':'',         'shall that':'', 
                   'that was':'',           'was that':'', 
                   'that will':'',          'will that':'', 
                   'that would':'',         'would that':'', 

                   'they are':'',           'are they':'', 
                   'they can':'',           'can they':'', 
                   'they could':'',         'could they':'', 
                   'they did':'',           'did they':'', 
                   'they do':'',            'do they':'', 
                   'they may':'',           'may they':'', 
                   'they might':'',         'might they':'', 
                   'they must':'',          'must they':'', 
                   'they shall':'',         'shall they':'', 
                   'they should':'',        'should they':'', 
                   'they were':'',          'were they':'', 
                   'they will':'',          'will they':'', 
                   'they would':'',         'would they':'', 

                   'this can':'',           'can this':'', 
                   'this could':'',         'could this':'', 
                   'this did':'',           'did this':'', 
                   'this does':'',          'does this':'', 
                   'this is':'',            'is this':'', 
                   'this may':'',           'may this':'', 
                   'this might':'',         'might':'', 
                   'this must':'',          'must this':'', 
                   'this shall':'',         'shall this':'', 
                   'this should':'',        'should this':'', 
                   'this was':'',           'was this':'', 
                   'this will':'',          'will this':'', 
                   'this would':'',         'would this':'', 

                   'we are':'',             'are we':'', 
                   'we can':'',             'can we':'', 
                   'we could':'',           'could we':'', 
                   'we did':'',             'did we':'', 
                   'we do':'',              'do we':'', 
                   'we may':'',             'may we':'', 
                   'we might':'',           'might we':'', 
                   'we must':'',            'must we':'', 
                   'we shall':'',           'shall we':'', 
                   'we should':'',          'should we':'', 
                   'we were':'',            'were we':'', 
                   'we will':'',            'will we':'', 
                   'we would':'',           'would we':'', 

                   'you are':'',            'are you':'', 
                   'you can':'',            'can you':'', 
                   'you could':'',          'could you':'', 
                   'you did':'',            'did you':'', 
                   'you do':'',             'do you':'', 
                   'you may':'',            'may you':'', 
                   'you might':'',          'might you':'', 
                   'you must':'',           'must you':'', 
                   'you shall':'',          'shall you':'', 
                   'you should':'',         'should you':'', 
                   'you were':'',           'were you':'', 
                   'you will':'',           'will you':'', 
                   'you would':'',          'would you':'', 
}

lang = input()
lst = lang.split()
result = ''

i_1 = 0
while i < len(lst):
    # try/except to see if the key is one word or two words
    try:
        if lst[i] in LANG_SYNTAX_1.values():  # Check if the word is LANG
            result += lst[i] + ' '
            i += 1
        else:
            result += LANG_SYNTAX_1[lst[i]] + ' '  # get the word from the dictionary
            i += 1
    except KeyError:
        result += LANG_SYNTAX[lst[i] + ' ' + lst[i+1]] + ' '
        i += 2

print("ENGLISH_1: ", lang)
print("LANG:", result)
